apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentic-rag-ingress
  namespace: agentic-rag
  labels:
    app.kubernetes.io/name: agentic-multimodal-rag
    app.kubernetes.io/part-of: agentic-multimodal-rag
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
